### ISSUE TITLE
this doesn't seem to find my shows

### ISSUE THREAD

**Issue by ghost** [daeks/Plex-TV-Analyzer#1]
Hi,

I have PHP enabled on my Mac and can run your code.

...but it shows empty every time.  I have tried adding token into the config film but that also doesn't change anything.

What am I missing (I can see no setup instructions).

thanks!
J.

**Comment by daeks** [comment]
Have you renamed config.example.php to config.php?
Is Plex Server installed on the same machine?

**Comment by ghost** [comment]
agh - Plex is on my NAS and Plex-TV-Analyzer is on my Mac.
